# GENERATED by scripts/generate-contracts.mjs. Do not edit.
API_VERSION = "v1"
EVENT_SPEC_VERSION = "woozoo.event/v1"
HEALTH_PATH = "/api/v1/health"
CONTRACT_SOURCE_DIGESTS = {
    "openapi.v1.json": "c566313d1f163856e0f2c1df40fd61c91b752b18e31a4ef1efdf9bd693c3957c",
    "event-envelope.v1.json": "ed1155b1fa397b0d108674aaf9c2231af69f0e659d53c9763b68cbfed206e5f3",
}
