# GENERATED by scripts/generate-contracts.mjs. Do not edit.
from typing import Literal, TypedDict

API_VERSION = "v1"
EVENT_SPEC_VERSION = "woozoo.event/v1"
MARKET_EVENT_SPEC_VERSION = "woozoo.market-event/v1"
MARKET_DOMAIN_EVENT_SPEC_VERSION = "woozoo.market-domain-events/v1"
MARKET_SOURCE = "binance_spot_public"
HEALTH_PATH = "/api/v1/health"
MARKET_STATUS_PATH_TEMPLATE = "/api/v1/markets/{symbol}/status"
CONTRACT_SOURCE_DIGESTS = {
    "openapi.v1.json": "37f871ea62d06b8266079ba92d16c140ee49dd5623f9b97182b00e6c8fc89a07",
    "event-envelope.v1.json": "1bca200d85e9e177b74c3f12ccab1b705a54e104cd85557cdb23e1c83073bad9",
    "market-event.v1.json": "6eedfb52b8d28748542a5851df6960b4b495e520f1386a0b4efca933069511dd",
    "market-domain-events.v1.json": "c0e883dc53c6394355c9baa70e4ef642307eb2a0f13ef0fe9cb581f6dcf2dfc4",
}

QualityStatusV1 = Literal["healthy", "degraded", "stale", "invalid", "reconnecting"]


class StreamWatermarkBindingV1(TypedDict):
    session_id: str
    stream: str
    last_sequence: int
    observed_at: str


class TradePayloadBindingV1(TypedDict):
    kind: Literal["trade"]
    price: str
    quantity: str
    buyer_maker: bool


class BookTickerPayloadBindingV1(TypedDict):
    kind: Literal["book_ticker"]
    bid_price: str
    bid_quantity: str
    ask_price: str
    ask_quantity: str
    event_time_source: Literal["received_at"]


class KlinePayloadBindingV1(TypedDict):
    kind: Literal["kline"]
    interval: Literal["1m", "5m", "1h", "4h"]
    open_time: str
    close_time: str
    open: str
    close: str
    high: str
    low: str
    base_volume: str
    trade_count: int
    closed: bool


MarketPayloadBindingV1 = TradePayloadBindingV1 | BookTickerPayloadBindingV1 | KlinePayloadBindingV1


class MarketEventBindingV1(TypedDict):
    event_id: str
    event_type: Literal["trade", "book_ticker", "kline"]
    schema_version: Literal["woozoo.market-event/v1"]
    source: Literal["binance_spot_public"]
    symbol: Literal["BTCUSDT", "ETHUSDT"]
    event_time: str
    received_at: str
    sequence: int
    raw_event_id: str
    raw_payload_hash: str
    correlation_id: str
    quality_status: QualityStatusV1
    quality_reasons: list[str]
    stream_watermark: StreamWatermarkBindingV1
    payload: MarketPayloadBindingV1


class MarketRawAppendedDataBindingV1(TypedDict):
    raw_event_id: str
    collector_session_id: str
    source: Literal["binance_spot_public"]
    stream: str
    symbol: Literal["BTCUSDT", "ETHUSDT"] | None
    source_dedupe_key: str
    source_event_time: str | None
    received_at: str
    raw_payload_hash: str
    classification: Literal["market", "operational_control", "quarantined"]


class MarketQualityChangedDataBindingV1(TypedDict):
    quality_event_id: str
    scope: str
    previous_status: QualityStatusV1
    new_status: QualityStatusV1
    reason_codes: list[str]
    observed_at: str
    raw_event_id: str | None
    recovery_required: bool


class MarketDomainAggregateBindingV1(TypedDict):
    type: str
    id: str
    version: int


class MarketRawAppendedEventBindingV1(TypedDict):
    spec_version: Literal["woozoo.event/v1"]
    event_id: str
    event_type: Literal["market.raw.appended.v1"]
    event_version: Literal[1]
    occurred_at: str
    published_at: str | None
    producer: Literal["market-data-worker"]
    correlation_id: str
    causation_id: str | None
    aggregate: MarketDomainAggregateBindingV1
    data: MarketRawAppendedDataBindingV1
    payload_hash: str


class MarketNormalizedRecordedEventBindingV1(TypedDict):
    spec_version: Literal["woozoo.event/v1"]
    event_id: str
    event_type: Literal["market.normalized.recorded.v1"]
    event_version: Literal[1]
    occurred_at: str
    published_at: str | None
    producer: Literal["market-data-worker"]
    correlation_id: str
    causation_id: str | None
    aggregate: MarketDomainAggregateBindingV1
    data: MarketEventBindingV1
    payload_hash: str


class MarketQualityChangedEventBindingV1(TypedDict):
    spec_version: Literal["woozoo.event/v1"]
    event_id: str
    event_type: Literal["market.quality.changed.v1"]
    event_version: Literal[1]
    occurred_at: str
    published_at: str | None
    producer: Literal["market-data-worker"]
    correlation_id: str
    causation_id: str | None
    aggregate: MarketDomainAggregateBindingV1
    data: MarketQualityChangedDataBindingV1
    payload_hash: str
