// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export const API_VERSION = "v1" as const;
export const EVENT_SPEC_VERSION = "woozoo.event/v1" as const;
export const MARKET_EVENT_SPEC_VERSION = "woozoo.market-event/v1" as const;
export const EVIDENCE_SNAPSHOT_SPEC_VERSION = "woozoo.evidence-snapshot/v1" as const;
export const EVIDENCE_DOMAIN_EVENT_SPEC_VERSION = "woozoo.evidence-domain-events/v1" as const;
export const PAPER_ORDER_SPEC_VERSION = "woozoo.paper-order/v1" as const;
export const PAPER_DOMAIN_EVENT_SPEC_VERSION = "woozoo.paper-domain-events/v1" as const;
export const PAPER_ACTIVATION_PHASE = 7 as const;
export const MARKET_SOURCE = "binance_spot_public" as const;
export const HEALTH_PATH = "/api/v1/health" as const;
export const MARKET_STATUS_PATH_TEMPLATE = "/api/v1/markets/{symbol}/status" as const;
export const EVIDENCE_PATH_TEMPLATE = "/api/v1/evidence/{evidence_id}" as const;
export const EVIDENCE_COMMAND_PATH = "/api/v1/commands/evidence-snapshots" as const;
export const CONTRACT_SOURCE_DIGESTS = {
  "openapi.v1.json": "cc2b20e07e8dcd4d1c42477f63ec39522360c5c10c4b51aafd93909bd992456f",
  "event-envelope.v1.json": "a244451fe765951a6e6246d3d03c68d6924876f9a5a3525a36101ec29ba9891b",
  "market-event.v1.json": "6eedfb52b8d28748542a5851df6960b4b495e520f1386a0b4efca933069511dd",
  "market-domain-events.v1.json": "c0e883dc53c6394355c9baa70e4ef642307eb2a0f13ef0fe9cb581f6dcf2dfc4",
  "evidence-snapshot.v1.json": "2e60fb66732bcdea794f9a6ecaa519cae3a1fd3fa5b5890f11839cdeb5e99b8c",
  "evidence-domain-events.v1.json": "af113814267e596fa453b5036a8f5d6e579fce133ee03efee9cca785d3f1d749",
  "paper-order.v1.json": "3c536d1e011c6f847a78c42bf43c56aef2b9be8352a32d20fd200c812dc9a081",
  "paper-domain-events.v1.json": "4ff361b3acd58174bd5d4ec394e58da66089df87d6be9873587cf7c5083d12a5",
  "risk-input.v1.json": "92bcaf8af96a4676eef5ed0777622e8933337d68d5f3c623b65c380ea3aa33a2",
  "risk-decision.v1.json": "3d3d8b34052fbcf21ec557051bffb5b713cfc6d95c220ee5ff35bc046e2bc1db",
  "kill-switch.v1.json": "c70ff8c0d61994a2400df4efe79bcadfeef65661591097e371959b232aadbc93",
  "risk-domain-events.v1.json": "51558ea615fafb3827c251f6a19f1800881b31740619b1378f8a68bdb5be9ee3",
  "prompt-manifest.v1.json": "d6ec20a8099119810f4d2c6099972fa00e232c17695168deaf34281df397c109",
  "agent-report.v1.json": "6b2521dee4976843e14c629911d6bda85f80577f2973b3ee7f05020083820950",
  "trade-proposal.v1.json": "8ecb4426d9199e102ead687513d6fc0e2c4a3e9ad40b3e2d996ffd085c81d4cf",
  "analysis-run.v1.json": "b5e9ae5bca1495a94b4f7d7d05e78319d527f7217057547319524ddf12660122",
  "analysis-audit.v1.json": "67d6e8ffcd97ebb065d0b9b1653f1d57dffa8f87fbe763bbcbc11921f0874661",
  "agent-domain-events.v1.json": "0bb08a32ef4f78d3a5b86635887fd4a1ad9dcf64d8b23ab2ee0165feaee89489",
  "risk-input.v2.json": "4fca44bdbb1a8b2e1bdaabfec5cf34f9a34263768c4ca4a803e038b3841e487a",
  "analysis-run.v2.json": "12882a5e8eb82c86c1cb24860798b42c3688ff44e4e735eb4834a4b10cd32df7",
  "analysis-run-view.v1.json": "b5eaecaf74a2d0be1db85dec0f0fd4caeb325efb38b6d7586181f34e5e4aa594",
  "risk-input.v3.json": "2e6019ebd7b38e755716ba1a44ab4f7f5d5504eb8e0339142b490af3a34646a8",
  "paper-order.v2.json": "3f86334598a10dced3b0d75507420f453c7888551c9b27381d989dd455ac0d84",
  "paper-approval.v1.json": "57df16b7a8846a7e72cabf31db0278784a7b34a94f3d45f8c153850c232e5a38",
  "paper-approval-revocation.v1.json": "e019a61bd4350b63c9e605e7b665dfb1a2b505aa81df54355ac7f99582df6654",
  "paper-execution-authorization.v1.json": "0bed79c7d469e077d7970f964485286ba53509ae9295436a88dd3b5f9e652e20",
  "approval-view.v1.json": "72aa3bdec35ce52d42e48e3e3a1237ce7c51b80f0c7949c2732a09c10f19374c",
  "local-session.v1.json": "6698a0d8be20ae5281a8820f635691adb432945727aa179ac482e2b44c63630e",
  "risk-domain-events.v2.json": "90aeb936e34084fbae0c54dd72b69ba4005dbf1016f4bbdca903a19dd2fb0b1d",
  "paper-domain-events.v2.json": "88a581b9e640eddc70d6bacb6c50fbfdcc9ad9a376def37f85f06224f78591ec",
  "testnet-order-preview.v1.json": "813d6ac4b1e977506916088684526d1d228e5daded4faf8d207ba3b96c47c63f",
  "testnet-risk-input.v1.json": "a99bb8d28a6b3aa7312e1b1c73ce6af46d48e05c60fd5caadae7af4e315afd81",
  "testnet-risk-decision.v1.json": "e54c53c623557d0cd40c824a86bac23f21464a10f6b48d957141f1b170e563cc",
  "testnet-approval.v1.json": "a75d7bd933b4beec78a3ee31390048d921068c8e830c02c86f5259605f45e206",
  "testnet-approval-revocation.v1.json": "0d61d08369b46fe2aff4394dc8f28c20270bf1c4503f14df14192b46e76551cc",
  "testnet-execution-authorization.v1.json": "8c0c7719b4a5693a63638fe6e43e84153e8dbd8385ae060071d9952ee19e840a",
  "testnet-gateway-command.v1.json": "1744418bb8a43ad933eba120bbd4f7cf91eff15cf8ce22eb8adfce2a1219d12c",
  "testnet-gateway-receipt.v1.json": "8454fffe2bf3e497633982afdef3c708254d7b57209646010e8b75d71a229481",
  "testnet-order.v1.json": "4b394c7bf778f21d623099bcf83e325d492559c48b391fea864935aae7ff9d22",
  "testnet-reconciliation.v1.json": "1c594b50db41bbeb1aa6f2b2385eedba436f4f47474f104f1ba1657dc70d5546",
  "testnet-account-generation.v1.json": "5b330025f14dd3bb83ede0a4a3c423b711de6e4880795020429fbd303f9d0b0c",
  "testnet-gateway-status.v1.json": "306b24906472a16420d3933168704797e01fa9ae000ebf5fdde2dd86fa155eb5",
  "testnet-domain-events.v1.json": "92185943efdc048e7066c7f1e746c8bbc77fcb5203bf32c3389db2e9ef9d2d07"
} as const;
export const RISK_INPUT_SPEC_VERSION = "woozoo.risk-input/v1" as const;
export const RISK_DECISION_SPEC_VERSION = "woozoo.risk-decision/v1" as const;
export const KILL_SWITCH_SPEC_VERSION = "woozoo.kill-switch/v1" as const;
export const RISK_DOMAIN_EVENT_SPEC_VERSION = "woozoo.risk-domain-events/v1" as const;
export const RISK_ACTIVATION_PHASE = 7 as const;
export const PROMPT_MANIFEST_SPEC_VERSION = "woozoo.prompt-manifest/v1" as const;
export const AGENT_REPORT_SPEC_VERSION = "woozoo.agent-report/v1" as const;
export const TRADE_PROPOSAL_SPEC_VERSION = "woozoo.trade-proposal/v1" as const;
export const ANALYSIS_RUN_SPEC_VERSION = "woozoo.analysis-run/v1" as const;
export const ANALYSIS_AUDIT_SPEC_VERSION = "woozoo.analysis-audit/v1" as const;
export const AGENT_DOMAIN_EVENT_SPEC_VERSION = "woozoo.agent-domain-events/v1" as const;
export const RISK_INPUT_V2_SPEC_VERSION = "woozoo.risk-input/v2" as const;
export const AGENT_ACTIVATION_PHASE = 7 as const;
export const ANALYSIS_RUN_V2_SPEC_VERSION = "woozoo.analysis-run/v2" as const;
export const RISK_INPUT_V3_SPEC_VERSION = "woozoo.risk-input/v3" as const;
export const PAPER_ORDER_V2_SPEC_VERSION = "woozoo.paper-order/v2" as const;
export const PAPER_APPROVAL_SPEC_VERSION = "woozoo.paper-approval/v1" as const;
export const PAPER_APPROVAL_REVOCATION_SPEC_VERSION = "woozoo.paper-approval-revocation/v1" as const;
export const PAPER_EXECUTION_AUTHORIZATION_SPEC_VERSION = "woozoo.paper-execution-authorization/v1" as const;
export const APPROVAL_VIEW_SPEC_VERSION = "woozoo.approval-view/v1" as const;
export const LOCAL_SESSION_SPEC_VERSION = "woozoo.local-session/v1" as const;
export const RISK_DOMAIN_EVENT_V2_SPEC_VERSION = "woozoo.risk-domain-events/v2" as const;
export const PAPER_DOMAIN_EVENT_V2_SPEC_VERSION = "woozoo.paper-domain-events/v2" as const;
export const TRADING_ROOM_ACTIVATION_PHASE = 7 as const;
export const TESTNET_ACTIVATION_PHASE = 8 as const;
export const TESTNET_CONTRACT_SPEC_VERSIONS = {
  "testnet-order-preview.v1.json": "woozoo.testnet-order-preview/v1",
  "testnet-risk-input.v1.json": "woozoo.testnet-risk-input/v1",
  "testnet-risk-decision.v1.json": "woozoo.testnet-risk-decision/v1",
  "testnet-approval.v1.json": "woozoo.testnet-approval/v1",
  "testnet-approval-revocation.v1.json": "woozoo.testnet-approval-revocation/v1",
  "testnet-execution-authorization.v1.json": "woozoo.testnet-execution-authorization/v1",
  "testnet-gateway-command.v1.json": "woozoo.testnet-gateway-command/v1",
  "testnet-gateway-receipt.v1.json": "woozoo.testnet-gateway-receipt/v1",
  "testnet-order.v1.json": "woozoo.testnet-order/v1",
  "testnet-reconciliation.v1.json": "woozoo.testnet-reconciliation/v1",
  "testnet-account-generation.v1.json": "woozoo.testnet-account-generation/v1",
  "testnet-gateway-status.v1.json": "woozoo.testnet-gateway-status/v1",
  "testnet-domain-events.v1.json": "woozoo.testnet-domain-events/v1"
} as const;
