// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export const API_VERSION = "v1" as const;
export const EVENT_SPEC_VERSION = "woozoo.event/v1" as const;
export const MARKET_EVENT_SPEC_VERSION = "woozoo.market-event/v1" as const;
export const EVIDENCE_SNAPSHOT_SPEC_VERSION = "woozoo.evidence-snapshot/v1" as const;
export const EVIDENCE_DOMAIN_EVENT_SPEC_VERSION = "woozoo.evidence-domain-events/v1" as const;
export const PAPER_ORDER_SPEC_VERSION = "woozoo.paper-order/v1" as const;
export const PAPER_DOMAIN_EVENT_SPEC_VERSION = "woozoo.paper-domain-events/v1" as const;
export const PAPER_ACTIVATION_PHASE = 7 as const;
export const MARKET_SOURCE = "binance_spot_public" as const;
export const HEALTH_PATH = "/api/v1/health" as const;
export const MARKET_STATUS_PATH_TEMPLATE = "/api/v1/markets/{symbol}/status" as const;
export const EVIDENCE_PATH_TEMPLATE = "/api/v1/evidence/{evidence_id}" as const;
export const EVIDENCE_COMMAND_PATH = "/api/v1/commands/evidence-snapshots" as const;
export const CONTRACT_SOURCE_DIGESTS = {
  "openapi.v1.json": "6ddb9eab12bcf7e61c1832358ce1d62a6fa65f6c6e0a3bdc032156301c6ff4e3",
  "event-envelope.v1.json": "a244451fe765951a6e6246d3d03c68d6924876f9a5a3525a36101ec29ba9891b",
  "market-event.v1.json": "6eedfb52b8d28748542a5851df6960b4b495e520f1386a0b4efca933069511dd",
  "market-domain-events.v1.json": "c0e883dc53c6394355c9baa70e4ef642307eb2a0f13ef0fe9cb581f6dcf2dfc4",
  "evidence-snapshot.v1.json": "2e60fb66732bcdea794f9a6ecaa519cae3a1fd3fa5b5890f11839cdeb5e99b8c",
  "evidence-domain-events.v1.json": "af113814267e596fa453b5036a8f5d6e579fce133ee03efee9cca785d3f1d749",
  "paper-order.v1.json": "3c536d1e011c6f847a78c42bf43c56aef2b9be8352a32d20fd200c812dc9a081",
  "paper-domain-events.v1.json": "4ff361b3acd58174bd5d4ec394e58da66089df87d6be9873587cf7c5083d12a5",
  "risk-input.v1.json": "92bcaf8af96a4676eef5ed0777622e8933337d68d5f3c623b65c380ea3aa33a2",
  "risk-decision.v1.json": "3d3d8b34052fbcf21ec557051bffb5b713cfc6d95c220ee5ff35bc046e2bc1db",
  "kill-switch.v1.json": "c70ff8c0d61994a2400df4efe79bcadfeef65661591097e371959b232aadbc93",
  "risk-domain-events.v1.json": "51558ea615fafb3827c251f6a19f1800881b31740619b1378f8a68bdb5be9ee3",
  "prompt-manifest.v1.json": "d6ec20a8099119810f4d2c6099972fa00e232c17695168deaf34281df397c109",
  "agent-report.v1.json": "6b2521dee4976843e14c629911d6bda85f80577f2973b3ee7f05020083820950",
  "trade-proposal.v1.json": "8ecb4426d9199e102ead687513d6fc0e2c4a3e9ad40b3e2d996ffd085c81d4cf",
  "analysis-run.v1.json": "15281db11f3f89b9a7e1d98fb4f29ab09cf160e94c2cd7a4892e9abe6da750a9",
  "analysis-audit.v1.json": "8cb5887a9f047b8f3fcc4c2011a3b271afb1de5af094da2595d095716bf6e831",
  "agent-domain-events.v1.json": "0bb08a32ef4f78d3a5b86635887fd4a1ad9dcf64d8b23ab2ee0165feaee89489",
  "risk-input.v2.json": "4fca44bdbb1a8b2e1bdaabfec5cf34f9a34263768c4ca4a803e038b3841e487a"
} as const;
export const RISK_INPUT_SPEC_VERSION = "woozoo.risk-input/v1" as const;
export const RISK_DECISION_SPEC_VERSION = "woozoo.risk-decision/v1" as const;
export const KILL_SWITCH_SPEC_VERSION = "woozoo.kill-switch/v1" as const;
export const RISK_DOMAIN_EVENT_SPEC_VERSION = "woozoo.risk-domain-events/v1" as const;
export const RISK_ACTIVATION_PHASE = 7 as const;
export const PROMPT_MANIFEST_SPEC_VERSION = "woozoo.prompt-manifest/v1" as const;
export const AGENT_REPORT_SPEC_VERSION = "woozoo.agent-report/v1" as const;
export const TRADE_PROPOSAL_SPEC_VERSION = "woozoo.trade-proposal/v1" as const;
export const ANALYSIS_RUN_SPEC_VERSION = "woozoo.analysis-run/v1" as const;
export const ANALYSIS_AUDIT_SPEC_VERSION = "woozoo.analysis-audit/v1" as const;
export const AGENT_DOMAIN_EVENT_SPEC_VERSION = "woozoo.agent-domain-events/v1" as const;
export const RISK_INPUT_V2_SPEC_VERSION = "woozoo.risk-input/v2" as const;
export const AGENT_ACTIVATION_PHASE = 7 as const;
