// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export const API_VERSION = "v1" as const;
export const EVENT_SPEC_VERSION = "woozoo.event/v1" as const;
export const MARKET_EVENT_SPEC_VERSION = "woozoo.market-event/v1" as const;
export const EVIDENCE_SNAPSHOT_SPEC_VERSION = "woozoo.evidence-snapshot/v1" as const;
export const EVIDENCE_DOMAIN_EVENT_SPEC_VERSION = "woozoo.evidence-domain-events/v1" as const;
export const PAPER_ORDER_SPEC_VERSION = "woozoo.paper-order/v1" as const;
export const PAPER_DOMAIN_EVENT_SPEC_VERSION = "woozoo.paper-domain-events/v1" as const;
export const PAPER_ACTIVATION_PHASE = 7 as const;
export const MARKET_SOURCE = "binance_spot_public" as const;
export const HEALTH_PATH = "/api/v1/health" as const;
export const MARKET_STATUS_PATH_TEMPLATE = "/api/v1/markets/{symbol}/status" as const;
export const EVIDENCE_PATH_TEMPLATE = "/api/v1/evidence/{evidence_id}" as const;
export const EVIDENCE_COMMAND_PATH = "/api/v1/commands/evidence-snapshots" as const;
export const CONTRACT_SOURCE_DIGESTS = {
  "openapi.v1.json": "6ddb9eab12bcf7e61c1832358ce1d62a6fa65f6c6e0a3bdc032156301c6ff4e3",
  "event-envelope.v1.json": "a244451fe765951a6e6246d3d03c68d6924876f9a5a3525a36101ec29ba9891b",
  "market-event.v1.json": "6eedfb52b8d28748542a5851df6960b4b495e520f1386a0b4efca933069511dd",
  "market-domain-events.v1.json": "c0e883dc53c6394355c9baa70e4ef642307eb2a0f13ef0fe9cb581f6dcf2dfc4",
  "evidence-snapshot.v1.json": "2e60fb66732bcdea794f9a6ecaa519cae3a1fd3fa5b5890f11839cdeb5e99b8c",
  "evidence-domain-events.v1.json": "af113814267e596fa453b5036a8f5d6e579fce133ee03efee9cca785d3f1d749",
  "paper-order.v1.json": "7368f9ff52c93d7571ecdb3349d46846c66cc0963f0d2591d4f7ef2881e2851d",
  "paper-domain-events.v1.json": "6b0a5abbb88b7fa408ed795eebee64e6dfcf45b40f4e043e75d26874c5767178"
} as const;
