// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export type PostgresDependencyBindingV1 = { required: true; status: "healthy" };
export type RedisDependencyBindingV1 = { required: false; authoritative: false; status: "healthy" | "unavailable" };
export type PlatformHealthBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  data: {
    service: "control-api";
    status: "healthy" | "degraded";
    trading_mode: "paper";
    dependencies: { postgres: PostgresDependencyBindingV1; redis: RedisDependencyBindingV1 };
  };
  meta: { resource_version: null; next_cursor: null };
};
export type DependencyUnavailableBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  error: { code: "DEPENDENCY_UNAVAILABLE"; message: "a required platform dependency is unavailable" };
  meta: { resource_version: null; next_cursor: null };
};
export const healthPath = "/api/v1/health" as const;
export type MarketEventBindingV1 = {
  event_id: string;
  event_type: "trade" | "book_ticker" | "kline";
  schema_version: "woozoo.market-event/v1";
  source: "binance_spot_public";
  symbol: "BTCUSDT" | "ETHUSDT";
  event_time: string;
  received_at: string;
  sequence: number;
  raw_event_id: string;
  raw_payload_hash: string;
  correlation_id: string;
  quality_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting";
  quality_reasons: string[];
  stream_watermark: { session_id: string; stream: string; last_sequence: number; observed_at: string };
  payload:
    | { kind: "trade"; price: string; quantity: string; buyer_maker: boolean }
    | { kind: "book_ticker"; bid_price: string; bid_quantity: string; ask_price: string; ask_quantity: string; event_time_source: "received_at" }
    | { kind: "kline"; interval: "1m" | "5m" | "1h" | "4h"; open_time: string; close_time: string; open: string; close: string; high: string; low: string; base_volume: string; trade_count: number; closed: boolean };
};
export type MarketStatusBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; data: { symbol: "BTCUSDT" | "ETHUSDT"; price: string; event_time: string; received_at: string; quality: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; quality_reasons: string[]; watermark: { session_id: string; stream: string; last_sequence: number; observed_at: string } }; meta: { resource_version: null; next_cursor: null } };
export type MarketStatusErrorBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; error: { code: "MARKET_NOT_FOUND" | "MARKET_PROJECTION_UNAVAILABLE"; message: string }; meta: { resource_version: null; next_cursor: null } };
export const marketStatusPathTemplate = "/api/v1/markets/{symbol}/status" as const;
export type MarketRawAppendedDataBindingV1 = { raw_event_id: string; collector_session_id: string; source: "binance_spot_public"; stream: string; symbol: "BTCUSDT" | "ETHUSDT" | null; source_dedupe_key: string; source_event_time: string | null; received_at: string; raw_payload_hash: string; classification: "market" | "operational_control" | "quarantined" };
export type MarketQualityChangedDataBindingV1 = { quality_event_id: string; scope: string; previous_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; new_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; reason_codes: string[]; observed_at: string; raw_event_id: string | null; recovery_required: boolean };
export type MarketDomainEventEnvelopeBindingV1<TType extends string, TData> = { spec_version: "woozoo.event/v1"; event_id: string; event_type: TType; event_version: 1; occurred_at: string; published_at: string | null; producer: "market-data-worker"; correlation_id: string; causation_id: string | null; aggregate: { type: string; id: string; version: number }; data: TData; payload_hash: string };
export type MarketDomainEventBindingV1 =
  | MarketDomainEventEnvelopeBindingV1<"market.raw.appended.v1", MarketRawAppendedDataBindingV1>
  | MarketDomainEventEnvelopeBindingV1<"market.normalized.recorded.v1", MarketEventBindingV1>
  | MarketDomainEventEnvelopeBindingV1<"market.quality.changed.v1", MarketQualityChangedDataBindingV1>;
