// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export type PostgresDependencyBindingV1 = { required: true; status: "healthy" };
export type RedisDependencyBindingV1 = { required: false; authoritative: false; status: "healthy" | "unavailable" };
export type PlatformHealthBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  data: {
    service: "control-api";
    status: "healthy" | "degraded";
    trading_mode: "paper";
    dependencies: { postgres: PostgresDependencyBindingV1; redis: RedisDependencyBindingV1 };
  };
  meta: { resource_version: null; next_cursor: null };
};
export type DependencyUnavailableBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  error: { code: "DEPENDENCY_UNAVAILABLE"; message: "a required platform dependency is unavailable" };
  meta: { resource_version: null; next_cursor: null };
};
export const healthPath = "/api/v1/health" as const;
export type MarketEventBindingV1 = {
  event_id: string;
  event_type: "trade" | "book_ticker" | "kline";
  schema_version: "woozoo.market-event/v1";
  source: "binance_spot_public";
  symbol: "BTCUSDT" | "ETHUSDT";
  event_time: string;
  received_at: string;
  sequence: number;
  raw_event_id: string;
  raw_payload_hash: string;
  correlation_id: string;
  quality_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting";
  quality_reasons: string[];
  stream_watermark: { session_id: string; stream: string; last_sequence: number; observed_at: string };
  payload:
    | { kind: "trade"; price: string; quantity: string; buyer_maker: boolean }
    | { kind: "book_ticker"; bid_price: string; bid_quantity: string; ask_price: string; ask_quantity: string; event_time_source: "received_at" }
    | { kind: "kline"; interval: "1m" | "5m" | "1h" | "4h"; open_time: string; close_time: string; open: string; close: string; high: string; low: string; base_volume: string; trade_count: number; closed: boolean };
};
export type MarketStatusBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; data: { symbol: "BTCUSDT" | "ETHUSDT"; price: string; event_time: string; received_at: string; quality: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; quality_reasons: string[]; watermark: { session_id: string; stream: string; last_sequence: number; observed_at: string } }; meta: { resource_version: null; next_cursor: null } };
export type MarketStatusErrorBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; error: { code: "MARKET_NOT_FOUND" | "MARKET_PROJECTION_UNAVAILABLE"; message: string }; meta: { resource_version: null; next_cursor: null } };
export const marketStatusPathTemplate = "/api/v1/markets/{symbol}/status" as const;
export type MarketRawAppendedDataBindingV1 = { raw_event_id: string; collector_session_id: string; source: "binance_spot_public"; stream: string; symbol: "BTCUSDT" | "ETHUSDT" | null; source_dedupe_key: string; source_event_time: string | null; received_at: string; raw_payload_hash: string; classification: "market" | "operational_control" | "quarantined" };
export type MarketQualityChangedDataBindingV1 = { quality_event_id: string; scope: string; previous_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; new_status: "healthy" | "degraded" | "stale" | "invalid" | "reconnecting"; reason_codes: string[]; observed_at: string; raw_event_id: string | null; recovery_required: boolean };
export type MarketDomainEventEnvelopeBindingV1<TType extends string, TData> = { spec_version: "woozoo.event/v1"; event_id: string; event_type: TType; event_version: 1; occurred_at: string; published_at: string | null; producer: "market-data-worker"; correlation_id: string; causation_id: string | null; aggregate: { type: string; id: string; version: number }; data: TData; payload_hash: string };
export type MarketDomainEventBindingV1 =
  | MarketDomainEventEnvelopeBindingV1<"market.raw.appended.v1", MarketRawAppendedDataBindingV1>
  | MarketDomainEventEnvelopeBindingV1<"market.normalized.recorded.v1", MarketEventBindingV1>
  | MarketDomainEventEnvelopeBindingV1<"market.quality.changed.v1", MarketQualityChangedDataBindingV1>;
export type EvidenceItemBindingV1 = { item_type: "normalized_market_event" | "feature_observation"; item_id: string; raw_event_id: string; raw_payload_hash: string };
export type EvidenceCandleBindingV1 = { normalized_event_id: string; raw_event_id: string; raw_payload_hash: string; interval: "1m" | "5m" | "1h" | "4h"; event_time: string; received_at: string; open_time: string; close_time: string; open: string; high: string; low: string; close: string; base_volume: string };
export type EvidenceFeatureBindingV1 = { feature_id: string; name: "close_return_1" | "close_sma_20" | "close_rsi_14"; definition_version: "woozoo.feature.ohlcv-return-sma20-rsi14/v1"; interval: "1m" | "5m" | "1h" | "4h"; feature_time: string; value: string; input_digest: string };
export type EvidenceSnapshotBindingV1 = { evidence_id: string; evidence_digest: string; symbol: "BTCUSDT" | "ETHUSDT"; as_of: string; knowledge_cutoff: string; recipe_version: "woozoo.evidence.closed-candles-approved-features/v1"; input_digest: string; quality: "healthy"; quality_reasons: []; collector_session_id: string; watermark_digest: string; items: EvidenceItemBindingV1[]; candles: EvidenceCandleBindingV1[]; features: EvidenceFeatureBindingV1[] };
export type EvidenceSnapshotEnvelopeBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; data: EvidenceSnapshotBindingV1; meta: { resource_version: null; next_cursor: null } };
export type EvidenceErrorBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; error: { code: "EVIDENCE_NOT_FOUND" | "EVIDENCE_PROJECTION_UNAVAILABLE"; message: string }; meta: { resource_version: null; next_cursor: null } };
export type EvidenceDomainEventBindingV1 = { spec_version: "woozoo.event/v1"; event_id: string; event_type: "evidence.snapshot.created.v1"; event_version: 1; occurred_at: string; published_at: string | null; producer: "evidence-worker"; correlation_id: string; causation_id: string | null; aggregate: { type: "evidence_snapshot"; id: string; version: number }; data: EvidenceSnapshotBindingV1; payload_hash: string };
export type EvidenceCommandBindingV1 = { symbol: "BTCUSDT" | "ETHUSDT"; as_of: string; knowledge_cutoff: string };
export type EvidenceCommandReceiptBindingV1 = { evidence_id: string; evidence_digest: string; created: boolean };
export type EvidenceCommandReceiptEnvelopeBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; data: EvidenceCommandReceiptBindingV1; meta: { resource_version: null; next_cursor: null } };
export type EvidenceCommandErrorEnvelopeBindingV1 = { api_version: "v1"; request_id: string; correlation_id: string; served_at: string; error: { code: "SCHEMA_INVALID" | "IDEMPOTENCY_CONFLICT" | "CALLER_UNAUTHORIZED" }; meta: { resource_version: null; next_cursor: null } };
export const evidencePathTemplate = "/api/v1/evidence/{evidence_id}" as const;
export const evidenceCommandPath = "/api/v1/commands/evidence-snapshots" as const;
export type PaperOrderBindingV1 = { order_id: string; client_order_id: string; authorization_id: string; authorization_namespace: "test"; symbol: "BTCUSDT" | "ETHUSDT"; side: "BUY" | "SELL"; order_type: "LIMIT"; time_in_force: "GTC"; quantity: string; limit_price: string; filled_quantity: string; status: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CANCELLED"; version: number };
export type PaperDomainEventEnvelopeBindingV1<TType extends string, TData> = { spec_version: "woozoo.event/v1"; event_id: string; event_type: TType; event_version: 1; occurred_at: string; producer: "paper-engine"; activation_phase: 7; aggregate_id: string; aggregate_version: number; payload_hash: string; data: TData };
export type PaperDomainEventBindingV1 =
  | PaperDomainEventEnvelopeBindingV1<"paper.order.accepted.v1", { order_id: string }>
  | PaperDomainEventEnvelopeBindingV1<"paper.order.partially-filled.v1" | "paper.order.filled.v1", { order_id: string; fill_id: string }>
  | PaperDomainEventEnvelopeBindingV1<"paper.order.cancelled.v1", { order_id: string; cancel_id: string }>
  | PaperDomainEventEnvelopeBindingV1<"paper.order.rejected.v1", { request_hash: string; reason: "INSUFFICIENT_FUNDS" }>
  | PaperDomainEventEnvelopeBindingV1<"paper.authorization.attempted.v1", { authorization_id: string; outcome: "BLOCKED" | "CONSUMED" }>
  | PaperDomainEventEnvelopeBindingV1<"ledger.transaction.posted.v1", { transaction_id: string }>;
export type RiskVerdictBindingV1 = "ALLOWED" | "DENIED" | "ERROR";
export type RiskDecisionBindingV1 = { decision_schema_version: "woozoo.risk-decision/v1"; decision_id: string; risk_input_digest: string; decision_hash: string; verdict: RiskVerdictBindingV1; primary_reason: string; ordered_reason_codes: string[]; policy_version: string; proposal_hash: string; portfolio_snapshot_hash: string; data_state_hash: string; paper_order_preview_hash: string; reconciliation_checkpoint_hash: string; kill_switch_version: number; decision_as_of: string };
export type KillSwitchBindingV1 = { scope: "paper-global"; active: true; prior_version: number; version: number; activation_event_id: string; trigger_kind: "MANUAL" | "INVARIANT"; actor_id: string; reason_code: "MANUAL_SAFETY_STOP" | "LEDGER_IMBALANCE" | "PHYSICAL_LEDGER_MISMATCH" | "AUTHORIZATION_RECEIPT_MISMATCH"; reason: string; observed_at: string; context_digest: string };
export type RiskDomainEventBindingV1 = { spec_version: "woozoo.event/v1"; event_id: string; event_type: "risk.decision.recorded.v1" | "kill-switch.activated.v1"; event_version: 1; occurred_at: string; producer: "risk-engine"; activation_phase: 7; aggregate_id: string; aggregate_version: number; payload_hash: string; data: RiskDecisionBindingV1 | KillSwitchBindingV1 };
export type AgentRoleBindingV1 = "MARKET_REGIME" | "TECHNICAL" | "TRADE_FLOW" | "BULL" | "BEAR" | "TRADER" | "PORTFOLIO" | "AUDIT";
export type AgentReportBindingV1 = { schema_version: "woozoo.agent-report/v1"; report_id: string; run_id: string; role: AgentRoleBindingV1; evidence_id: string; evidence_digest: string; as_of: string; knowledge_cutoff: string; symbol: "BTCUSDT" | "ETHUSDT"; evidence_item_ids: string[]; dependency_report_ids: string[]; claim_times: string[]; findings: string[]; uncertainty: string[]; invalidation_conditions: string[]; confidence: string; stance: "BUY" | "SELL" | "HOLD" | "NEUTRAL"; provider: "mock"; model: "woozoo-deterministic-mock/v1"; prompt_manifest_hash: string; workflow_hash: string; report_hash: string };
export type TradeProposalBindingV1 = { schema_version: "woozoo.trade-proposal/v1"; proposal_id: string; proposal_version: "v1"; analysis_run_id: string; evidence_id: string; evidence_digest: string; as_of: string; knowledge_cutoff: string; symbol: "BTCUSDT" | "ETHUSDT"; side: "BUY" | "SELL" | "HOLD"; risk_eligible: boolean; report_ids: string[]; report_hashes: string[]; evidence_item_ids: string[]; thesis: string; uncertainty: string[]; invalidation_conditions: string[]; confidence: string; provider: "mock"; model: "woozoo-deterministic-mock/v1"; prompt_manifest_hash: string; workflow_version: "woozoo.agent-workflow/v1"; workflow_hash: string; proposal_hash: string };
export type AnalysisRunBindingV1 = { schema_version: "woozoo.analysis-run/v1"; run_id: string; namespace: "test"; evidence_id: string; evidence_digest: string; symbol: "BTCUSDT" | "ETHUSDT"; as_of: string; knowledge_cutoff: string; workflow_version: "woozoo.agent-workflow/v1"; workflow_hash: string; prompt_manifest_hash: string; provider: "mock"; model: "woozoo-deterministic-mock/v1"; outcome: "COMPLETED" | "HOLD"; hold_reason: string | null; report_ids: string[]; proposal_id: string | null; audit_hash: string };
