// GENERATED by scripts/generate-contracts.mjs. Do not edit.
export type PostgresDependencyBindingV1 = { required: true; status: "healthy" };
export type RedisDependencyBindingV1 = { required: false; authoritative: false; status: "healthy" | "unavailable" };
export type PlatformHealthBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  data: {
    service: "control-api";
    status: "healthy" | "degraded";
    trading_mode: "paper";
    dependencies: { postgres: PostgresDependencyBindingV1; redis: RedisDependencyBindingV1 };
  };
  meta: { resource_version: null; next_cursor: null };
};
export type DependencyUnavailableBindingV1 = {
  api_version: "v1";
  request_id: string;
  correlation_id: string;
  served_at: string;
  error: { code: "DEPENDENCY_UNAVAILABLE"; message: "a required platform dependency is unavailable" };
  meta: { resource_version: null; next_cursor: null };
};
export const healthPath = "/api/v1/health" as const;
